---
galaxy_info:
  author: josephdelnordd
  description: Role de maintenance serveur (paquets, monitoring, banniere SSH)
  license: GPL-3.0-or-later
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - system
    - maintenance
    - monitoring
    - ssh

dependencies: []
